from django.test import TestCase

# Create your tests here.
# Generated by Selenium IDE

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLoginTest(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_loginTest(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "username").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "username").send_keys("will")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".mt-4").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "password").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "password").send_keys("PasswordlyPass#21!")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

# Generated by Selenium IDE

class TestMovieSearch(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_movieSearch(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.NAME, "query").click()
        time.sleep(2)
        self.driver.find_element(By.NAME, "query").send_keys("Chitty Chitty Bang Bang")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-light").click()


# Generated by Selenium IDE

class TestTestBlocked(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testBlocked(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".fa-ban").click()


# Generated by Selenium IDE

class TestTestDetails(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testDetails(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "My Watchlist").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Details").click()


# Generated by Selenium IDE

class TestTestFilter(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testFilter(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        time.sleep(2)
        self.driver.find_element(By.ID, "genre_28").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "genre_99").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_min_release_year").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_min_release_year").send_keys("2000")
        time.sleep(2)
        self.driver.find_element(By.ID, "id_max_release_year").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_max_release_year").send_keys("2020")
        time.sleep(2)
        self.driver.find_element(By.ID, "id_min_rating").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_min_rating").send_keys("5")
        time.sleep(2)
        self.driver.find_element(By.ID, "saveFilters").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "clearFilters").click()


# Generated by Selenium IDE

class TestTestHeart(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testHeart(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".fa-heart").click()


# Generated by Selenium IDE

class TestTestMovieDetailOptions(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testMovieDetailOptions(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "My Watchlist").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Details").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-danger").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-warning").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-success").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "My Watchlist").click()


# Generated by Selenium IDE

class TestTestNavbarButtons(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testNavbarButtons(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "My Watchlist").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Discover").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "FlickFinder").click()


# Generated by Selenium IDE

class TestTestRemove(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testRemove(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "My Watchlist").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".col-xl-3:nth-child(1) .btn:nth-child(1)").click()


# Generated by Selenium IDE

class TestTestSkip(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testSkip(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 822)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".action-btn > .fa-times").click()
        time.sleep(2)
        element = self.driver.find_element(By.CSS_SELECTOR, ".action-btn > .fa-times")
        time.sleep(2)
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()


# Generated by Selenium IDE

class TestTestSwipe(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testSwipe(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "body").click()
        time.sleep(2)
        element = self.driver.find_element(By.CSS_SELECTOR, ".movie-poster")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()


# Generated by Selenium IDE

class TestTestWishlist(TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_testWishlist(self):
        self.driver.get("http://54.224.150.215/")
        self.driver.set_window_size(1440, 900)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".text-success").click()

