# Generated by Django 5.1.6 on 2025-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickFinder', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='genre_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
