# Generated by Django 5.1.6 on 2025-04-05 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickFinder', '0004_alter_userfilter_genre_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='genre_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='usermovieinteraction',
            index=models.Index(fields=['user', 'interaction_type', 'timestamp'], name='flickFinder_user_id_fd6b96_idx'),
        ),
    ]
