# Generated by Django 5.1.6 on 2025-04-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickFinder', '0005_alter_usermovieinteraction_interaction_type'),
        ('flickFinder', '0005_movie_genres_movie_vote_average_movie_vote_count_and_more'),
    ]

    operations = [
    ]
