# Generated by Django 5.1.6 on 2025-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickFinder', '0006_merge_20250409_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.JSONField(blank=True, help_text="List of genre dicts, e.g., [{'id': 28, 'name': 'Action'}]", null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(help_text='TMDB unique identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(blank=True, help_text='Should have minimum of 100 votes', null=True),
        ),
    ]
