# Generated by Django 5.1.6 on 2025-04-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickFinder', '0006_merge_20250409_1948'),
        ('flickFinder', '0007_alter_movie_genres_alter_movie_vote_count'),
    ]

    operations = [
    ]
