# Generated by Django 5.1.6 on 2025-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickFinder', '0008_merge_20250414_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(help_text='TMDB unique identifier', unique=True),
        ),
    ]
